# Generated by Django 5.0.3 on 2024-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
